services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1420:1420"
    volumes:
      # Mount source code for live editing
      - .:/app
      # Anonymous volumes to preserve dependencies and cache
      - /app/node_modules
      - /app/target
      - /app/.cargo
    environment:
      - RUST_BACKTRACE=1
    privileged: true
    network_mode: "host"
